{% set version = "1.8.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-distr6
  version: {{ version|replace("-", "_") }}

source:
  url: https://raphaels1.r-universe.dev/src/contrib/distr6_{{ version }}.tar.gz
  sha256: c33d52d2934d3d420f12c4c8bb98adaa

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate
    - r-data.table
    - r-param6 >=0.2.4
    - r-r6
    - r-rcpp
    - r-set6 >=0.2.6
  run:
    - r-base
    - r-checkmate
    - r-data.table
    - r-param6 >=0.2.4
    - r-r6
    - r-rcpp
    - r-set6 >=0.2.6

test:
  commands:
    - $R -e "library('distr6')"           # [not win]
    - "\"%R%\" -e \"library('distr6')\""  # [win]

about:
  home: https://alan-turing-institute.github.io/distr6/
  dev_url: https://github.com/alan-turing-institute/distr6/
  license: MIT
  summary: An R6 object oriented distributions package. Unified interface for 42 probability distributions and 11 kernels including functionality for multiple scientific types. Additionally functionality for composite distributions and numerical imputation. Design patterns including wrappers and decorators are described
    in Gamma et al. (1994, ISBN:0-201-63361-2). For quick reference of probability distributions including d/p/q/r functions and results we refer to McLaughlin, M. P. (2001). Additionally Devroye (1986, ISBN:0-387-96305-7) for sampling the Dirichlet distribution, Gentle (2009) <doi:10.1007/978-0-387-98144-4> for sampling
    the Multivariate Normal distribution and Michael et al. (1976) <doi:10.2307/2683801> for sampling the Wald distribution.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - pascal-git
